services:
  - docker
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "8"
  - "9"

script: "npm install && npm run ci"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
